### ISSUE TITLE
Fix for table names with spacing

### ISSUE THREAD

**Issue by maxkraft7** [Austyns/sqlite-to-json-python#5]
I have a sqlite database where the tablenames contain spaces (I don't like it either). By modifying [this](https://github.com/Austyns/sqlite-to-json-python/blob/3484202b1827053e8bcc97a23fa2598634414073/import_all.py#L23) line to `curs.execute("SELECT * FROM '{}' ".format(table_name))` I was able to make your script work with these tablenames aswell.

**Comment by Austyns** [comment]
Thanks, @maxkraft7
[This PR](https://github.com/Austyns/sqlite-to-json-python/pull/6) fixes that
